version: "3"
services:
  octoprint:
    build: ./
    image: dcagatay/octoprint:latest
    container_name: octoprint
    ports:
      - 5000:5000
    # devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
     - ./config:/home/octoprint/.octoprint
    restart: unless-stopped
